const businessCategories = [
  "Consulting",
  "Software Development",
  "Marketing",
  "Jewelry & Watches",
  "Retail",
  "Health & Wellness",
  "Real Estate",
  "Education",
  "Finance",
  "Legal Services",
  "Design",
  "Hospitality",
  "E-commerce",
  "Construction",
  "Transportation & Logistics",
  "Manufacturing",
  "Entertainment & Media",
  "Human Resources",
  "Technology Services",
  "Nonprofit & Charity",
  "Automotive Services",
  "Travel & Tourism",
  "Food & Beverage",
  "Event Planning",
  "Art & Culture",
  "Telecommunications",
  "Agriculture & Farming",
  "Environmental Services",
  "Fashion & Apparel",
  "Public Relations",
  "Healthcare & Medical",
  "Sports & Recreation",
  "Home Services & Repair",
  "Beauty & Personal Care",
];
export default businessCategories;
